Repository opensrp/fhircore, pull requests merged in 2023-07, with the labels that each got.

#2516 Fixes & Enhancements
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/di/FhirEngineModule.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/di/NetworkModule.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/sync/SyncBroadcaster.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/SharedPreferencesHelper.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistryTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/data/local/DefaultRepositoryTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/util/SharedPreferencesHelperTest.kt
  android/gradle/libs.versions.toml
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/appsetting/AppSettingViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/LoginViewModel.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/appsetting/AppSettingViewModelTest.kt
Labels: 0.2.4

#2519 Fix sync timestamp not updating (#2518)
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/app/ApplicationConfiguration.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/di/CoreModule.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/sync/AppSyncWorker.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/sync/OpenSrpDownloadManager.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/sync/SyncBroadcaster.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/sync/AppSyncWorkerTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/sync/SyncBroadcasterTest.kt
  android/gradle/libs.versions.toml
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/appsetting/AppSettingViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainActivity.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingViewModel.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/main/AppMainActivityTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModelTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingFragmentTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingViewModelTest.kt
Labels: 0.2.4

#2515 add configuration to generate MeasureReports in the background
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/report/measure/MeasureReportConfiguration.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/MeasureExtensions.kt
  android/quest/src/main/assets/configs/app/reports/service_delivery_measure_report_config.json
  android/quest/src/main/assets/configs/app/reports/supply_chain_measure_report_config.json
  android/quest/src/main/java/org/smartregister/fhircore/quest/data/report/measure/MeasureReportPagingSource.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/data/report/measure/MeasureReportRepository.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/data/report/measure/MeasureReportSubjectsPagingSource.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/MeasureReportViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/worker/MeasureReportConfigWorker.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/util/extensions/WorkManagerExtensions.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/data/report/measure/MeasureReportPagingSourceTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/data/report/measure/MeasureReportSubjectsPagingSourceTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/report/measure/MeasureReportViewModelTest.kt
Labels: 0.2.4

#2524 Fix change HH head breaking if a HH head is not already assigned
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/data/local/DefaultRepositoryTest.kt
Labels: 0.2.4

#2513 Configure fab button animation
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/navigation/NavigationMenuConfig.kt
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/ui/shared/components/ExtendedFabTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/ExtendedFab.kt
Labels: 0.2.4

#2530 Close sick child workflow automatically
  CHANGELOG.md
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt
Labels: 0.2.4

#2533 Fix trigger to remove resource on opensrp-0.2.4
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivity.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
Labels: 0.2.4

#2539 :bug: Remove the minus 1 day condition for tasks to be marked as ready
  CHANGELOG.md
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorkerTest.kt
Labels: 0.2.4

#2546 add subjects in existing report retrieval
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/MeasureReportViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/worker/MeasureReportConfigWorker.kt
Labels: 0.2.4

#2553 Add latest enhancements and bug fixes
  android/engine/build.gradle.kts
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/QuestionnaireConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/event/EventTriggerCondition.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/event/EventWorkflow.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/navigation/NavigationMenuConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/profile/ManagingEntityConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/register/NoResultsConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/register/RegisterCardConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/ButtonProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/CardViewProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/ColumnProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/CompoundTextProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/DividerProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/ImageProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/ListProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/PersonalDataProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/RowProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/ServiceCardProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/SpacerProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/ViewProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/workflow/ActionTrigger.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/ActionConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/FhirResourceConfigs.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/OverflowMenuItemConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/RuleConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/SnackBarMessageConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/TopBarConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/ResourceDataRulesExecutor.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskExpireWorker.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskUtil.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/ResourceExtension.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/rulesengine/RulesEngineServiceTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirTaskExpireWorkerTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorkerTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirTaskUtilTest.kt
  android/gradle/libs.versions.toml
  android/quest/src/main/assets/configs/app/profiles/default_profile_config.json
  android/quest/src/main/assets/configs/app/profiles/household_profile_config.json
  android/quest/src/main/java/org/smartregister/fhircore/quest/event/AppEvent.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/event/EventQueue.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/navigation/MainNavigationScreen.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainActivity.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/profile/ProfileFragment.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivity.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterFragment.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/QuestionnaireHandler.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/util/extensions/ConfigExtensions.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/event/EventBusTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/main/AppMainActivityTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/register/RegisterFragmentTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/shared/model/QuestionnaireHandlerTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/util/extensions/ConfigExtensionsTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/util/extensions/WorkManagerExtensionsTest.kt
Labels: 0.2.4

#2554 Update p2p query to match new indexes
  android/engine/src/main/java/org/smartregister/fhircore/engine/p2p/dao/BaseP2PTransferDao.kt
Labels: 0.2.4

#2552 Catch non-HttpException errors when fetching keycloak user
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/LoginViewModel.kt
Labels: 0.2.4

#2556 Dismiss sync loader dialog when percentage is more than 100%
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/components/register/LoaderView.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainActivity.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterFragment.kt
Labels: 0.2.4

#2557 Configure fab button animation (#2513)
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/navigation/NavigationMenuConfig.kt
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/ui/shared/components/ExtendedFabTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/ExtendedFab.kt
Labels: 0.2.4

#2558 OpenSRP Release 0.2.4 RC 3
  android/quest/build.gradle.kts
Labels: 0.2.4

#2560 fix error in household and member deactivation based on questionnaire…
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
Labels: 0.2.4

#2544 Catch non-HttpException errors when fetching keycloak user
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/LoginViewModel.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/login/LoginViewModelTest.kt
Labels: DNM

#2604 [MWCore] Internal release 0.1.10
  android/quest/build.gradle
Labels: Malawi CORE

#2607 Add enableFamilyRegistration test for GeoWidgetfragment
  android/geowidget/src/test/java/org/smartregister/fhircore/geowidget/screens/GeoWidgetFragmentTest.kt
Labels: DNM, Code Health

#2612 Documentation of spacer and divider widgets.
  docs/engineering/android-app/Configurations/user-interface/widget-config.mdx
Labels: Documentation, Technical Debt

#2614 Add View and Row widget documentation
  docs/engineering/android-app/Configurations/user-interface/widget-config.mdx
Labels: Documentation, Technical Debt

#2618 Add form authoring consideration documentation
  docs/engineering/android-app/writing-fhir/form-authoring.mdx
Labels: Documentation, Discussion

#2611 Add automated release notes
  .github/release
Labels: Draft, DNM
