Repository opensrp/fhircore, pull requests merged in 2023-06, with the labels that each got.

#2414 Fix loading secondary resource data to Rules Engine
  android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/rulesengine/RulesFactoryTest.kt
Labels: Priority - High

#2407 Update the CarePlan Closure configs to define the PlanDefs to close separately
  CHANGELOG.md
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/QuestionnaireConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/event/EventTriggerCondition.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/event/EventType.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/event/EventWorkflow.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/FhirResourceConfigs.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/KeyValueConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/configuration/QuestionnaireConfigTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
Labels: Work In Progress

#2397 [Quest/Malawi Core] Resource Not Found Bug
  android/engine/build.gradle
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
Labels: Malawi CORE

#2420 [MWCore] Internal release 0.1.7
  android/quest/build.gradle
Labels: Malawi CORE

#2423 [MWCore] Fix Crashlytics
  android/quest/src/main/java/org/smartregister/fhircore/quest/QuestApplication.kt
Labels: Malawi CORE

#2429 [MWCore] Internal release 0.1.8
  android/quest/build.gradle
Labels: Malawi CORE

#2428 Fix the PinTest.testPinCellsEqualsToPinInput test
  android/engine/src/androidTest/java/org/smartregister/fhircore/engine/ui/components/PinTest.kt
Labels: FHIR Core, Code Health

#2469 [OpenSRP 2] Fix sync failure - Regression
  android/gradle/libs.versions.toml
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterFragment.kt
  android/quest/src/test/assets/configs/app/application_config.json
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/register/RegisterFragmentTest.kt
Labels: OpenSRP 2

#2478 Update the pregnant icon to color purple
  android/engine/src/main/res/drawable/ic_pregnant.xml
Labels: 0.2.3 Final Release

#2435 Implement Image widget
  CHANGELOG.md
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/navigation/NavigationBottomSheetRegisterConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/navigation/NavigationMenuConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/ButtonProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/CompoundTextProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/ImageProperties.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view/ViewPropertiesSerializer.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/OverflowMenuItemConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/ViewType.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/configuration/view/ImageProportiesTest.kt
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/ui/shared/components/ActionableButtonTest.kt
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/ui/shared/components/ExtendedFabTest.kt
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/ui/shared/components/ViewGeneratorTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/AppDrawer.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/profile/ProfileScreen.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/ActionableButton.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/CompoundText.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/ExtendedFab.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/Image.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/MenuIcon.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/ViewGenerator.kt
  android/quest/src/main/res/drawable/ic_add.xml
  android/quest/src/main/res/drawable/ic_cancel.xml
  android/quest/src/main/res/drawable/ic_check.xml
  android/quest/src/main/res/drawable/ic_due.xml
  android/quest/src/main/res/drawable/ic_green_tick.xml
  android/quest/src/main/res/drawable/ic_overdue.xml
Labels: DNM

#2487 Migrate Engine Artifact
  android/gradle/libs.versions.toml
Labels: 0.2.3 Final Release

#2483 Fix issue [2146] Update dependant tasks due date
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/ResourceExtension.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
Labels: 0.2.3 Final Release

#2465 [Quest/Malawi]Fix resetting of tasks to READY
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/dao/HivRegisterDao.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt
Labels: Malawi CORE

#2491 Questionnaires that have the confirmationDialog config are not extracted | 0.2.3 - Release
  CHANGELOG.md
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivity.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivityTest.kt
Labels: 0.2.3 Final Release

#2496 [MWCore] Internal release 0.1.9
  android/quest/build.gradle
Labels: Malawi CORE
