Repository opensrp/fhircore, pull requests merged in 2023-11, with the labels that each got.

#2859 [MWCore] Resume previous activity on login from background
  android/quest/src/main/java/org/smartregister/fhircore/quest/QuestApplication.kt
Labels: Malawi CORE

#2855 1399 order of household register
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
Labels: Documentation

#2880 Refactor client to support FHIR Gateway Plugins backend
  android/engine/src/main/java/org/smartregister/fhircore/engine/OpenSrpApplication.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/di/NetworkModule.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/StringExtensions.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/util/extension/StringExtensionTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/QuestApplication.kt
Labels: DNM

#2860 Add Onboarding docs for info gateway
  docs/engineering/android-app/developer-setup/keycloak-auth-token-config.md
  docs/engineering/android-app/developer-setup/publishing-fhir-sdk-artifacts.mdx
  docs/engineering/android-app/readme.mdx
  docs/engineering/backend/architecture.mdx
  docs/engineering/backend/info-gateway.mdx
  docs/engineering/backend/keycloak.mdx
  docs/engineering/backend/readme.mdx
Labels: Documentation, Server Side
