Repository opensrp/fhircore, pull requests merged in 2023-09, with the labels that each got.

#2719 Add test to RegisterCardList
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/integration/ui/register/components/RegisterCardListTest.kt
Labels: Code Health

#2724 Use action parameters in RulesEngine
  android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/ResourceDataRulesExecutor.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/rulesengine/RulesFactoryTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/data/register/RegisterPagingSource.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterUiState.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterViewModel.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/data/register/RegisterPagingSourceTest.kt
Labels: 0.2.5

#2725 [Quest/Malawi Core] Filter guardian task using the meta tag
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/app/ApplicationConfiguration.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/configuration/app/ApplicationConfigurationTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/profile/PatientProfileViewModel.kt
Labels: Malawi CORE

#2732 Fix save last sync timestamp
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirResourceUtil.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt
  android/engine/src/main/res/values/strings.xml
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainActivity.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterFragment.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/CqlContentTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/util/extensions/WorkManagerExtensionsTest.kt
Labels: 0.2.5

#2736 Log CarePlan generation error in Timber
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
Labels: 0.2.5

#2737 Show sync dialog until first time sync completes successfully
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
Labels: 0.2.5

#2741 Add an else statement for when the Task is null
  android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt
Labels: 0.2.5

#2742 [MWCore] - Fix crash occurring on authentication fails after initial log-in
  android/engine/src/main/java/org/smartregister/fhircore/engine/auth/AccountAuthenticator.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/remote/shared/TokenAuthenticator.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/di/CoreModule.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/sync/SyncBroadcaster.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/auth/AccountAuthenticatorTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/auth/TokenAuthenticatorTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/sync/SyncBroadcasterTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/ui/userprofile/UserProfileViewModelTest.kt
Labels: Malawi CORE

#2767 Upgrade sdk dependencies
  android/engine/src/main/java/org/smartregister/fhircore/engine/sync/AppSyncWorker.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/sync/OpenSrpDownloadManager.kt
  android/engine/src/test/resources/register-patient-missingitems/missingitem-questionnaire.json
  android/gradle/libs.versions.toml
  android/quest/src/test/resources/patient-registration-questionnaire/questionnaire.json
  docs/engineering/android-app/developer-setup/publishing-fhir-sdk-artifacts.mdx
Labels: Discussion, Work In Progress

#2785 Add onCreate test to QuestApplication
  android/quest/src/test/java/org/smartregister/fhircore/quest/QuestApplicationTest.kt
Labels: Code Health
