Repository opensrp/fhircore, pull requests merged in 2023-08, with the labels that each got.

#2622 Refactor questionnaire implementation
  android/engine/build.gradle.kts
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/QuestionnaireConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/cql/LibraryEvaluator.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/QuestionnaireType.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskUtil.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/base/AlertDialogue.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/base/BaseMultiLanguageActivity.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/SharedPreferenceKey.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/AndroidExtensions.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/QuestionnaireExtension.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/ResourceExtension.kt
  android/engine/src/main/res/layout/activity_questionnaire.xml
  android/engine/src/main/res/values/styles.xml
  android/engine/src/test/java/org/smartregister/fhircore/engine/configuration/QuestionnaireConfigTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/cql/LibraryEvaluatorTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/domain/model/QuestionnaireTypeTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/ui/base/AlertDialogueTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/util/extension/QuestionnaireExtensionTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/util/extension/ResourceExtensionTest.kt
  android/geowidget/build.gradle.kts
  android/quest/build.gradle.kts
  android/quest/src/main/AndroidManifest.xml
  android/quest/src/main/java/org/smartregister/fhircore/quest/QuestConfigService.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/navigation/NavigationArg.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainActivity.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivity.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireProgressState.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/QuestionnaireHandler.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/models/QuestionnaireSubmission.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/util/extensions/ConfigExtensions.kt
  android/quest/src/main/res/drawable/ic_arrow_back.xml
  android/quest/src/main/res/layout/questionnaire_activity.xml
  android/quest/src/main/res/values-night/themes.xml
  android/quest/src/main/res/values/strings.xml
  android/quest/src/main/res/values/themes.xml
  android/quest/src/test/java/org/smartregister/fhircore/quest/CqlContentTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivityTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/shared/model/QuestionnaireHandlerTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/util/extensions/ConfigExtensionsTest.kt
Labels: Work In Progress

#2636 [Opensrp 0.2.5] Add progress indicator for report generation
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/MeasureReportMainScreen.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/screens/MeasureReportListScreen.kt
Labels: 0.2.5

#2655 Rename measure report screen title
  android/engine/src/main/res/values/strings.xml
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/MeasureReportMainScreen.kt
Labels: 0.2.5

#2668 Address reports showing duplicate entries per subject.
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/MeasureReportViewModel.kt
Labels: 0.2.5

#2649 Interpolate ActionConfig.workflow for Profiles and Questionnaires
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/QuestionnaireConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/ActionConfig.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/domain/model/ActionConfigTest.kt
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/integration/ui/shared/components/ActionableButtonTest.kt
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/integration/ui/shared/components/ExtendedFabTest.kt
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/integration/ui/shared/components/ViewGeneratorTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/profile/ProfileViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/util/extensions/ConfigExtensions.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModelTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/util/extensions/ConfigExtensionsTest.kt
Labels: Enhancement, App Configuration

#2683 update eCBIS preview icons
  android/quest/src/ecbis_preview/res/drawable/ic_launcher.png
  android/quest/src/ecbis_preview/res/drawable/ic_launcher.xml
Labels: 0.2.5

#2693 Issue2642
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/data/remote/fhir/resource/FhirResourceDataSourceTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/login/LoginViewModelTest.kt
  docs/engineering/android-app/getting-started/readme.mdx
Labels: Testing

#2699 OpenSRP 0.2.5 v1
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskUtil.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirTaskUtilTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/util/SharedPreferencesHelperTest.kt
  android/quest/build.gradle.kts
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/MeasureReportViewModel.kt
Labels: 0.2.5

#2688 [MWCore] Bug fixes and updates
  android/engine/src/main/java/org/smartregister/fhircore/engine/auth/AccountAuthenticator.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/dao/HivRegisterDao.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/login/LoginViewModel.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/app/fakes/Faker.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/auth/AccountAuthenticatorTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/data/local/register/dao/HivRegisterDaoTest.kt
  android/quest/build.gradle
  android/quest/src/main/java/org/smartregister/fhircore/quest/AppInActivityListener.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/QuestApplication.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
Labels: Malawi CORE

#2712 Refactor FhirResourceUtils for Optimization
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskUtil.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirTaskUtilTest.kt
Labels: 0.2.5

#2713 Update the eCBIS training app name and fix a bug
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt
  android/quest/build.gradle.kts
  android/quest/src/ecbis_training/res/drawable/ic_app_logo.xml
  android/quest/src/ecbis_training/res/drawable/ic_launcher.png
Labels: 0.2.5

#2682 echis - 2489 - hh register tasklist status for hh item
  android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/rulesengine/RulesEngineServiceTest.kt
Labels: 0.2.5
