Repository opensrp/fhircore, pull requests merged in 2023-10, with the labels that each got.

#2781 0.2.5 Practitioner report supply chain fix
  android/engine/build.gradle.kts
  android/engine/src/main/java/org/smartregister/fhircore/engine/cql/R4MeasureProcessorExt.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/ReflectionUtil.kt
  android/gradle/libs.versions.toml
  android/quest/build.gradle.kts
  android/quest/src/main/java/org/smartregister/fhircore/quest/data/report/measure/MeasureReportRepository.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/MeasureReportViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/worker/MeasureReportConfigWorker.kt
Labels: 0.2.5

#2790 added support of Immunization protocolApplied for dosageNumber
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/helper/TransformSupportServices.kt
  android/quest/src/test/resources/patient-registration-questionnaire/questionnaire-response.json
  android/quest/src/test/resources/patient-registration-questionnaire/structure-map.txt
Labels: 0.2.5

#2748 [MWCore] - Add settings/Info page
  android/dataclerk/src/main/java/org/dtree/fhircore/dataclerk/ui/home/HomeScreen.kt
  android/dataclerk/src/main/java/org/dtree/fhircore/dataclerk/ui/info/InfoScreen.kt
  android/dataclerk/src/main/java/org/dtree/fhircore/dataclerk/ui/main/AppMainViewModel.kt
  android/dataclerk/src/main/java/org/dtree/fhircore/dataclerk/ui/main/AppScreen.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/login/LoginViewModel.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/settings/DevViewModel.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/settings/InfoCard.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/settings/ProfileData.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/settings/SettingsScreen.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/settings/SettingsViewModel.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/settings/views/DevMenu.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/settings/views/ViewResources.kt
  android/engine/src/main/res/values/strings.xml
  android/engine/src/test/java/org/smartregister/fhircore/engine/ui/login/LoginViewModelTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/ui/settings/SettingsScreenKtTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainScreen.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/AppDrawer.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/profile/PatientProfileViewModel.kt
  android/quest/src/main/res/xml/file_paths.xml
Labels: Malawi CORE

#2798 Add more tests to onCreate in QuestApplication class
  android/quest/src/test/java/org/smartregister/fhircore/quest/QuestApplicationTest.kt
Labels: Code Health

#2799 Increase runTest timeout to 60s for failing test
  android/engine/src/test/java/org/smartregister/fhircore/engine/ui/login/LoginViewModelTest.kt
Labels: Malawi CORE

#2802 [MWCore] Internal release 0.1.15
  android/quest/build.gradle
Labels: Malawi CORE

#2792 Update title on MeasureReportResultScreen andMeasureReportPopulationResultView
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/integration/ui/report/measure/components/MeasureReportPopulationResultViewTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/components/MeasureReportPopulationResultView.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/screens/MeasureReportResultScreen.kt
Labels: DNM, In-app Reports

#2796 Update Configuration Documentation
  docs/engineering/android-app/configurations/user-interface/navigation-config.mdx
  docs/engineering/android-app/configurations/user-interface/register-config.mdx
  docs/engineering/android-app/configurations/user-interface/widget-config.mdx
Labels: DNM

#2807 [MWCore] Update to latest engine sdk
  android/dataclerk/src/main/java/org/dtree/fhircore/dataclerk/data/QuestXFhirQueryResolver.kt
  android/dataclerk/src/main/java/org/dtree/fhircore/dataclerk/ui/main/AppDataStore.kt
  android/engine/build.gradle
  android/engine/src/main/java/org/smartregister/fhircore/engine/appointment/MissedFHIRAppointmentsWorker.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/appointment/ProposedWelcomeServiceAppointmentsWorker.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/cql/LibraryEvaluator.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/dao/AncPatientRegisterDao.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/dao/AppointmentRegisterDao.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/dao/DefaultPatientRegisterDao.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/dao/FamilyRegisterDao.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/dao/HivRegisterDao.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/dao/TracingRegisterDao.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/tracing/TracingRepository.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/remote/fhir/resource/FhirXFhirQueryResolver.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/remote/shared/TokenAuthenticator.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/p2p/dao/BaseP2PTransferDao.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/sync/SyncBroadcaster.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/WelcomeServiceBackToCarePlanWorker.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/questionnaire/QuestionnaireViewModel.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/settings/DevViewModel.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/ApplicationExtension.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/FhirEngineExtension.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/app/fakes/Faker.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/appointment/MissedFHIRAppointmentsWorkerTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/data/local/DefaultRepositoryTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/data/local/register/dao/AppointmentRegisterDaoTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/data/local/register/dao/HivRegisterDaoTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/data/local/register/dao/TracingRegisterDaoTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/data/local/tracing/TracingRepositoryTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/sync/SyncBroadcasterTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorkerTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/WelcomeServiceBackToCarePlanWorkerTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/ui/questionnaire/QuestionnaireViewModelTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/util/extension/ApplicationExtensionTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/data/patient/PatientRepository.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/data/task/PatientTaskRepository.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/util/PatientUtil.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/app/fakes/Faker.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/data/PatientRepositoryTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/data/PatientTaskRepositoryTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/util/PatientUtilTest.kt
Labels: Malawi CORE

#2823 [MWCore] Inject Library with javax.inject.provider
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/appsetting/AppSettingActivity.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/questionnaire/QuestionnaireActivity.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/questionnaire/QuestionnaireViewModel.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/ui/questionnaire/QuestionnaireActivityTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/ui/questionnaire/QuestionnaireViewModelTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/details/ListDataDetailViewModel.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/patient/details/ListDataDetailViewModelTest.kt
Labels: Malawi CORE

#2832 Update the Questionnaire documentation
  docs/engineering/android-app/configurations/questionnaire-config.mdx
Labels: Documentation

#2834 [MWCore] Tracing updates
  android/engine/build.gradle
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/dao/TracingRegisterDao.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/sync/SyncBroadcaster.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/TracingHelpers.kt
  android/quest/build.gradle
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/report/measure/MeasureReportViewModel.kt
Labels: Malawi CORE
