Repository opensrp/fhircore, pull requests merged in 2024-01, with the labels that each got.

#2938 Migrate plugins to version catalog
  android/build.gradle.kts
  android/gradle/libs.versions.toml
  android/settings.gradle.kts
Labels: Code Health

#2959 [MWCore] Update refresh token to avoid reuse of stale refresh token
  android/engine/src/main/java/org/smartregister/fhircore/engine/auth/AccountAuthenticator.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/remote/shared/TokenAuthenticator.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/auth/AccountAuthenticatorTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/auth/TokenAuthenticatorTest.kt
Labels: Malawi CORE

#2965 Add Dynamic data pass between profiles and questionnaires documentation
  docs/engineering/android-app/configuring/config-types/application.mdx
  docs/engineering/android-app/configuring/config-types/questionnaire.mdx
  docs/engineering/android-app/configuring/working-with-rules.mdx
Labels: Documentation, Code Health

#2969 Fix data migration issues
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/QuestionnaireConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/migration/MigrationConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/profile/ProfileConfiguration.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/ResourceExtension.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/util/extension/ResourceExtensionTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/data/DataMigration.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
Labels: DNM

#2909 Application Database Download
  android/engine/src/main/res/values/strings.xml
  android/quest/build.gradle.kts
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingScreenTest.kt
  android/quest/src/main/AndroidManifest.xml
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingFragment.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingScreen.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingsEvent.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/util/DBUtils.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/util/FileUtils.kt
  android/quest/src/main/res/xml/file_paths.xml
Labels: 0.2.5

#2991 Add icons for SID apps
  android/quest/src/sidBunda/res/drawable/ic_app_logo.png
  android/quest/src/sidBunda/res/drawable/ic_launcher.png
  android/quest/src/sidCadre/res/drawable/ic_app_logo.png
  android/quest/src/sidCadre/res/drawable/ic_launcher.png
  android/quest/src/sidEir/res/drawable/ic_app_logo.png
  android/quest/src/sidEir/res/drawable/ic_launcher.png
Labels: User Interface & Experience

#2961 [MWCore] Update engine sdk to v0.1.0-beta04-preview4.2-SNAPSHOT
  android/engine/build.gradle
Labels: Malawi CORE

#2993 [MWCore] Internal release 0.1.21 - Prod 0.0.9
  android/quest/build.gradle
Labels: Malawi CORE

#3015 Implement service functions v0.2.5
  android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/services/DateService.kt
Labels: 0.2.5

#3001 Refactor data migration to use ResourceConfig
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/migration/MigrationConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/RegisterRepository.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/services/DateService.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/ResourceExtension.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/data/DataMigration.kt
Labels: 0.2.5

#3017 [MWCore] Tracing updates
  android/deps.gradle
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/app/ApplicationConfiguration.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/dao/HivRegisterDao.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/domain/util/DataLoadState.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/questionnaire/QuestionnaireViewModel.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/settings/InfoCard.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/settings/SettingsViewModel.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/data/local/register/dao/HivRegisterDaoTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/ui/questionnaire/QuestionnaireActivityTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/ui/questionnaire/QuestionnaireViewModelTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/ui/settings/InfoCardTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/ui/settings/SettingsScreenKtTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/patient/profile/PatientProfileScreen.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/tracing/profile/TracingProfileViewModel.kt
Labels: Malawi CORE
