Repository opensrp/fhircore, pull requests merged in 2024-08, with the labels that each got.

#3425 [MLS] Add Spanish Translations
  android/engine/src/main/res/values-es/strings.xml
  android/engine/src/main/res/values/strings.xml
  android/geowidget/src/main/java/org/smartregister/fhircore/geowidget/screens/GeoWidgetFragment.kt
  android/quest/src/contigo/res/values-es/strings.xml
Labels: UNICEF Mexico

#3332 Sync progress enhancement work.
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/theme/Colors.kt
  android/engine/src/main/res/drawable/ic_variant_loader.xml
  android/engine/src/main/res/values/strings.xml
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/integration/ui/main/components/AppDrawerTest.kt
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/integration/ui/register/RegisterScreenTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/launcher/GeoWidgetLauncherFragment.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/launcher/GeoWidgetLauncherViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainActivity.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainEvent.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainUiState.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/AppDrawer.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterFragment.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterScreen.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterUiState.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/Image.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/SyncStatusView.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/models/AppDrawerUIState.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingFragment.kt
  android/quest/src/main/res/values/strings.xml
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/register/RegisterFragmentTest.kt
Labels: Work In Progress

#2874 Validate extracted fhir resources while in debug
  android/engine/build.gradle.kts
  android/engine/src/main/java/org/smartregister/fhircore/engine/di/FhirValidatorModule.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/FhirValidatorExtension.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/util/extension/FhirValidatorExtensionTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
  android/quest/src/main/res/values/strings.xml
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
Labels: DNM

#3451 Fix sync UI
  android/engine/src/main/res/values-es/strings.xml
  android/engine/src/main/res/values-fr/strings.xml
  android/engine/src/main/res/values-in/strings.xml
  android/engine/src/main/res/values-sw/strings.xml
  android/engine/src/main/res/values/strings.xml
  android/geowidget/src/main/java/org/smartregister/fhircore/geowidget/screens/GeoWidgetFragment.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/geowidget/GeoWidgetLauncherFragment.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/geowidget/GeoWidgetLauncherScreen.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/geowidget/GeoWidgetLauncherViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/AppDrawer.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterFragment.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterScreen.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/SyncStatusView.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingScreen.kt
  android/quest/src/main/res/layout/fragment_geo_widget_launcher.xml
  android/quest/src/main/res/navigation/application_nav_graph.xml
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/geowidget/GeoWidgetLauncherViewModelTest.kt
Labels: Work In Progress

#3463 Update strings.xml
  android/quest/src/contigo/res/values-es/strings.xml
Labels: UNICEF Mexico
