Repository opensrp/fhircore, pull requests merged in 2024-09, with the labels that each got.

#3475 :memo: Fix broken links on the documentation
  docs/engineering/app/configuring/writing-fhir/sample-fhir-resources/readme.mdx
Labels: Documentation

#3485 Filtering service points issue fixed
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterViewModel.kt
Labels: EUSM

#3502 [EIR] Add Reference Content
  docs/engineering/getting-started/_category_.yml
  docs/engineering/getting-started/app-setup.mdx
  docs/engineering/getting-started/server-setup.mdx
  docs/engineering/quickstart-guide/_category_.yml
  docs/engineering/quickstart-guide/running-the-app.mdx
  docs/engineering/quickstart-guide/server-setup.mdx
  docs/features/supported-health-domains/immunization.mdx
  docs/features/supported-health-domains/readme.mdx
  static/img/eir_configs/application-config.png
  static/img/eir_configs/caregiver-profile.png
  static/img/eir_configs/caregiver-register.png
  static/img/eir_configs/child-profile.png
  static/img/eir_configs/child-register.png
  static/img/eir_configs/composition-config.png
  static/img/eir_configs/ig-config.png
  static/img/eir_configs/immunization-pd.png
  static/img/eir_configs/list.png
  static/img/eir_configs/location-config.png
  static/img/eir_configs/navigation-config.png
  static/img/eir_configs/questionnaire_config.png
  static/img/eir_configs/strings-en.png
  static/img/eir_configs/strings-es.png
  static/img/eir_configs/sync-config.png
  static/img/eir_screenshoots/add-child.png
  static/img/eir_screenshoots/adverse-reaction.png
  static/img/eir_screenshoots/authentication.png
  static/img/eir_screenshoots/caregiver-profile.png
  static/img/eir_screenshoots/caregiver-register.png
  static/img/eir_screenshoots/caregiver-search.png
  static/img/eir_screenshoots/child-profile.png
  static/img/eir_screenshoots/homepage-es.png
  static/img/eir_screenshoots/immunization-form.png
  static/img/eir_screenshoots/insights-page.png
  static/img/eir_screenshoots/login.png
  static/img/eir_screenshoots/maps.png
  static/img/eir_screenshoots/mls-support.png
  static/img/eir_screenshoots/navigation-drawer-es.png
  static/img/eir_screenshoots/navigation-drawer.png
  static/img/eir_screenshoots/overflow-menu.png
  static/img/eir_screenshoots/past-encounters.png
  static/img/eir_screenshoots/pending-sync.png
  static/img/eir_screenshoots/permissions.png
  static/img/eir_screenshoots/record-adverse-reaction.png
  static/img/eir_screenshoots/registration-es.png
  static/img/eir_screenshoots/registration.png
  static/img/eir_screenshoots/set-pin.png
  static/img/eir_screenshoots/sync-complete.png
  static/img/eir_screenshoots/syncing.png
  static/img/eir_screenshoots/upcoming-encounters.png
  static/img/eir_screenshoots/user-settings.png
Labels: PATH GIZ EIR
