Repository opensrp/fhircore, pull requests merged in 2024-03, with the labels that each got.

#3115 Downgrade data-capture library supporting location-widget
  android/engine/src/main/res/values/attrs.xml
  android/engine/src/main/res/values/dimens.xml
  android/engine/src/main/res/values/styles.xml
  android/gradle/libs.versions.toml
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivity.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireItemViewHolderFactoryMatchersProviderFactoryImpl.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
Labels: 0.2.5

#3094 Add Data Migration documentation to docusite
  docs/engineering/android-app/configuring/add-application-flavors.mdx
  docs/engineering/android-app/configuring/config-types/_category_.yml
  docs/engineering/android-app/configuring/data-migration.mdx
  docs/engineering/android-app/configuring/event-management/_category_.yml
  docs/engineering/android-app/configuring/in-app-reporting.mdx
  docs/engineering/android-app/configuring/working-with-rules.mdx
Labels: Documentation

#3062 Test register screen composable
  android/engine/src/main/java/org/smartregister/fhircore/engine/ui/components/register/LoaderDialog.kt
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/integration/ui/register/RegisterScreenTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterScreen.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/components/RegisterCardList.kt
Labels: Code Health
