Repository opensrp/fhircore, pull requests merged in 2024-11, with the labels that each got.

#3530 Adding the sync strategies documentations
  docs/engineering/admin-dashboard/readme.mdx
  docs/engineering/app/datastore/tagging.mdx
  docs/engineering/backend/info-gateway/readme.mdx
  docs/engineering/backend/info-gateway/sync-strategies.mdx
  docs/features/admin-dashboard-features/readme.mdx
Labels: Documentation

#3461 Caching questionnaires and their SM
  .github/workflows/ci.yml
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/ContentCache.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepositoryComponent.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/data/local/ContentCacheTest.kt
  android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
  android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
  android/engine/src/test/resources/plans/disease-followup/structure-map.txt
  android/engine/src/test/resources/plans/household-routine-visit/structure-map.txt
  android/quest/build.gradle.kts
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/LoginActivity.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
Labels: Performance (App or Server)

#3616 Fix Home Register not refreshing after initial sync 🐛
  android/engine/src/main/java/org/smartregister/fhircore/engine/sync/SyncBroadcaster.kt
Labels: Bug-fix

#3484 Added progress indicator on Insight Screen
  .github/workflows/ci.yml
  android/engine/src/main/res/values-es/strings.xml
  android/engine/src/main/res/values-fr/strings.xml
  android/engine/src/main/res/values-in/strings.xml
  android/engine/src/main/res/values-sw/strings.xml
  android/engine/src/main/res/values/strings.xml
  android/quest/src/androidTest/java/org/smartregister/fhircore/quest/integration/ui/usersetting/UserSettingInsightScreenTest.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/usersetting/UserInsightScreenFragment.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingInsightScreen.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingScreen.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/robolectric/RobolectricTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/usersetting/UserInsightScreenFragmentTest.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/usersetting/UserSettingFragmentTest.kt
Labels: DNM
