Repository opensrp/fhircore, pull requests merged in 2024-02, with the labels that each got.

#3027 [MWCore] Internal release 0.1.22 - Prod 0.1.0
  android/quest/build.gradle
Labels: Malawi CORE

#3030 Fix add group member and change group resource managing entity
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/QuestionnaireConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/migration/MigrationConfig.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt
  android/engine/src/main/java/org/smartregister/fhircore/engine/di/FhirEngineModule.kt
  android/engine/src/main/res/values/strings.xml
  android/engine/src/test/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistryTest.kt
  android/gradle/libs.versions.toml
  android/quest/src/main/java/org/smartregister/fhircore/quest/data/DataMigration.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/event/AppEvent.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/ConfigDownloadWorker.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/LoginActivity.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/LoginScreen.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/login/LoginViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterFragment.kt
  android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/RegisterScreen.kt
  android/quest/src/test/java/org/smartregister/fhircore/quest/app/ConfigurationRegistryTest.kt
Labels: 0.2.5

#3031 Test changemanagingentity opens bottomsheet model
  android/quest/src/test/java/org/smartregister/fhircore/quest/ui/profile/ProfileViewModelTest.kt
Labels: Code Health
